apiVersion: kubedb.com/v1alpha1
kind: MySQL
metadata:
  name: my-mysql
#  namespace: demo
spec:
  version: "5.7-v2"
  replicas: 1
  storageType: Durable
  storage:
    storageClassName: "local-path"
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 50Mi
  updateStrategy:
    type: "RollingUpdate"
  terminationPolicy: WipeOut